# НАСТРОЙКИ НАГРУЗОЧНОГО ТЕСТИРОВАНИЯ 
# Начальная нагрузка 
start_load = 5
# Максимальная нагрузка
finish_load = 20

# Тестовая БД
testdb = default
# testdb = demo

# Тип синтетической нагрузки 
load_mode = olap
#load_mode = oltp

# Параметры Пуассоновского распределения
# 0 : Пуассоновское распределение - не применяется . Рост нагрузки экспоненциально
period_hours = 0
# period_hours = 2
# БЕСКОНЕЧНЫЙ ТЕСТ. 
# ДЛЯ ОСТАНОВКИ 
# /postgres/pg_expecto/sh/load_test/load_test_stop.sh
# period_hours = -1 
average_load = 0
# average_load = 40
# Имитация инцидента - vacuum
vacuum_incident = 0
#vacuum_incident = 1

# Веса сценариев по умолчанию
scenario1 = 0.7
scenario2 = 0.2
scenario3 = 0.1

# Инициализировать тестовую БД
init_test_db = on
#init_test_db = off

# Размер тестовой БД
# ~200MB
#scale = 20 

#~10GB
scale = 685



